openapi: 3.0.0

info:
  title: Glints-IPE-Group1-ToDoList
  description: ToDoList mini project API
  version: 1.0.0

servers:
  - url: https://glints1-todolist.herokuapp.com
    description: Backend main server

tags:
  - name: Auth
    description: User authentication and authorization
  - name: Activity
    description: Operations on activity object
paths:
  /sign-up:
    post:
      tags:
        - Auth
      summary: Register a new user to the server
      description: ''
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - password
      responses:
        '201':
          description: User registered to the application successfully
        '400':
          description: Bad Request. One of form data did NOT meet the requirement.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        msg:
                          type: string
                        param:
                          type: string
                        location:
                          type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /login:
    post:
      tags:
        - Auth
      summary: Login to the application with email and password
      description: 'Dummy account -> user@thisapp.com | passwordUser'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
                  isAdmin:
                    type: boolean
                  refresh_token:
                    type: string
                  access_token:
                    type: string
        '401': # status code
          description: Unauthorized. Credentials incorrect
  /forget-password:
    post:
      tags:
        - Auth
      summary: Request server to send link to reset password to user's email.
      description: ''
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: Operation success. Email sent to the user.
        '404':
          description: Email not found in the database
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /reset-password/{resetToken}:
    post:
      tags:
        - Auth
      summary: Change user's password
      description: ''
      parameters:
        - in: path
          name: resetToken # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: request token from the email
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                password:
                  type: string
              required:
                - password
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Password rejected. Must be at least 8 characters long.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Reset token is incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /activity:
    get:
      tags:
      - Activity
      summary: Get all activity of current user
      description: ''
      security:
        - access_token: []
      parameters:
        - in: header
          name: refresh_token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Operation success
          headers:
            new_access_token:
              schema:
                type: string
              description: Only available after refreshing token. Use this token for next api calls.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    hasImage:
                      type: boolean
                    image_url:
                      type: string
                    isDone:
                      type: boolean
        '403':
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      tags:
      - Activity
      summary: Save new activity to the database
      description: ''
      security:
        - access_token: []
      parameters:
        - in: header
          name: refresh_token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
                - title
                - description
      responses:
        '201':
          description: Activity saved to the database
          headers:
            new_access_token:
              schema:
                type: string
              description: Only available after refreshing token. Use this token for next api calls.
          
        '400':
          description: Bad Request. One of form data did NOT meet the requirement.
          headers:
            new_access_token:
              schema:
                type: string
              description: Only available after refreshing token. Use this token for next api calls.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        msg:
                          type: string
                        param:
                          type: string
                        location:
                          type: string
        '403':
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /activity/{id}:
    put:
      tags:
      - Activity
      summary: Edit activity detail
      description: ''
      security:
        - access_token: []
      parameters:
        - in: path
          name: id # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: activity's id
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                isDone:
                  type: boolean
              required:
                - title
                - description
                - isDone
      responses:
        '200':
          description: Activity saved to the database
          headers:
            new_access_token:
              schema:
                type: string
              description: Only available after refreshing token. Use this token for next api calls.
        '400':
          description: Bad Request. One of form data did NOT meet the requirement.
          headers:
            new_access_token:
              schema:
                type: string
              description: Only available after refreshing token. Use this token for next api calls.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        msg:
                          type: string
                        param:
                          type: string
                        location:
                          type: string
        '403':
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Cannot find activity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      tags:
      - Activity
      summary: Delete an activity from the database
      description: ''
      security:
        - access_token: []
      parameters:
        - in: path
          name: id # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: activity's id
      responses:
        '200':
          description: Activity deleted from the database
          headers:
            new_access_token:
              schema:
                type: string
              description: Only available after refreshing token. Use this token for next api calls.
        '400':
          description: Invalid activity id
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Cannot find activity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      
components:
  securitySchemes:
    access_token: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
